# Uses env vars GAR_HOST, PROJECT_ID & REPO_ID, and secrets SERVICE_ACCOUNT_KEY

name: Build and Push to Artifact Registry
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        default: "test"

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  GAR_HOST: ${{ vars.GAR_HOST }}
  GAR_LOCATION: ${{ vars.GAR_HOST }}${{ vars.PROJECT_ID }}/${{ vars.REPO_ID }}/data-sync:${{ github.sha }}

jobs:
  print-vars:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: "Print vars"
        run: echo "env.PROJECT_ID ${{ env.PROJECT_ID }}; vars.PROJECT_ID ${{ vars.PROJECT_ID }}; PROJECT_ID $PROJECT_ID"
  build-push-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: '${{ vars.PROJECT_ID }}'
          workload_identity_provider: projects/${{ vars.PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_HOST }} --quiet

      - name: Build image
        run: docker build . --file DOCKERFILE_LOCATION --tag ${{ env.GAR_LOCATION }}
        working-directory: WORKING_DIRECTORY

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
